InstantDelivery.Web/Models/PackageCostModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace InstantDelivery.Web.Models
{
    public class PackageCostModel
    {
        /// <summary>
        /// Waga paczki
        /// </summary>
        [RegularExpression("\\d+((\\.)\\d+)?", ErrorMessage = "Wprowadź poprawną liczbę")]
        [Required(ErrorMessage = "To pole jest wymagane")]
        [Range(1, 150, ErrorMessage = "Paczka posiada niedopuszczalną wagę")]
        [DisplayName("Waga [kg]")]
        public decimal Weight { get; set; }

        /// <summary>
        /// Wysokość paczki
        /// </summary>
        [RegularExpression("\\d+((\\.)\\d+)?", ErrorMessage = "Wprowadź poprawną liczbę")]
        [Required(ErrorMessage = "To pole jest wymagane")]
        [Range(1, 100, ErrorMessage = "Paczka posiada niedopuszczalną wysokość")]
        [DisplayName("Wysokość [cm]")]
        public double Height { get; set; }

        /// <summary>
        /// Szerokość paczki
        /// </summary>
        [RegularExpression("\\d+((\\.)\\d+)?", ErrorMessage = "Wprowadź poprawną liczbę")]
        [Required(ErrorMessage = "To pole jest wymagane")]
        [Range(1, 100, ErrorMessage = "Paczka posiada niedopuszczalną szerokość")]
        [DisplayName("Szerokość [cm]")]
        public double Width { get; set; }

        /// <summary>
        /// Długość paczki
        /// </summary>
        [RegularExpression("\\d+((\\.)\\d+)?", ErrorMessage = "Wprowadź poprawną liczbę")]
        [Required(ErrorMessage = "To pole jest wymagane")]
        [Range(1, 250, ErrorMessage = "Paczka posiada niedopuszczalną długość")]
        [DisplayName("Długość [cm]")]
        public double Length { get; set; }
    }
}

InstantDelivery.Web/Controllers/HomeController.cs
using System.Web.Mvc;

namespace InstantDelivery.Web.Controllers
{
    /// <summary>
    /// Główny kontroler aplikacji
    /// </summary>
    public class HomeController : Controller
    {
        /// <summary>
        /// Strona główna
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Strona "O nas"
        /// </summary>
        /// <returns></returns>
        public ActionResult About()
        {
            return View();
        }
    }
}

InstantDelivery.Web/Controllers/PackageController.cs
using InstantDelivery.Model.Packages;
using InstantDelivery.Web.Models;
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Globalization;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace InstantDelivery.Web.Controllers
{
    /// <summary>
    /// Kontroler zwracający widoki związane z paczkami
    /// </summary>
    public class PackageController : Controller
    {
        private const string baseUri = "https://instantdelivery.azurewebsites.net/api/";
        private readonly HttpClient client = new HttpClient();

        public PackageController()
        {
            client.BaseAddress = new Uri(baseUri);
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        }

        /// <summary>
        /// Pokazuje historię zdarzeń związanych z daną paczką
        /// </summary>
        /// <param name="packageId"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<ActionResult> Track(int packageId)
        {
            ViewBag.PackageId = packageId;
            var response = await client.GetAsync($"packages/{packageId}/history");
            if (response.IsSuccessStatusCode)
            {
                var dtos = await response.Content.ReadAsAsync<IEnumerable<PackageEventDto>>();
                return View(dtos);
            }
            return View();
        }

        /// <summary>
        /// Wyświetla formularz do obliczenia kosztu paczki
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Cost()
        {
            return View();
        }

        /// <summary>
        /// Wyświetla wynik obliczenia kosztu paczki
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> Cost(PackageCostModel model)
        {
            if (ModelState.IsValid)
            {
                string query = BuildQueryString(model);
                var response = await client.GetAsync($"packages/cost?{query}");
                if (response.IsSuccessStatusCode)
                {
                    var cost = await response.Content.ReadAsAsync<decimal>();
                    ViewBag.Cost = cost;
                    return View(model);
                }
            }
            return View();
        }

        private string BuildQueryString(PackageCostModel model)
        {
            NameValueCollection queryString = HttpUtility.ParseQueryString(string.Empty);
            queryString[nameof(PackageDto.Height)] = model.Height.ToString(CultureInfo.InvariantCulture);
            queryString[nameof(PackageDto.Width)] = model.Width.ToString(CultureInfo.InvariantCulture);
            queryString[nameof(PackageDto.Length)] = model.Length.ToString(CultureInfo.InvariantCulture);
            queryString[nameof(PackageDto.Weight)] = model.Weight.ToString(CultureInfo.InvariantCulture);
            return queryString.ToString();
        }
    }
}

InstantDelivery.Web/Controllers/PortalController.cs
using System.Web.Mvc;

namespace InstantDelivery.Web.Controllers
{
    public class PortalController : Controller
    {
        /// <summary>
        /// Punkt wejścia dla aplikacji SPA (portalu dla użytkowników)
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }
    }
}

InstantDelivery.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "O nas";
}

<div class="container">
    <div class="section">
        <h2>@ViewBag.Title.</h2>
        <p>Jesteśmy młodą firmą oferującą usługi kurierskie na terenie całej Polski.</p>
    </div>
</div>

InstantDelivery.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@section Scripts
{
    <script>
        $('.carousel').carousel({
            interval: 15000
        });
    </script>
}
<div id="myCarousel" class="carousel slide">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <div class="carousel-inner">
        <div class="item active">
            <div class="fill" style="background-image: url('../../Content/Resources/img3.jpg');"></div>
            <div class="carousel-caption">
                <h1>Instant Delivery - dostarczymy twoje paczki do celu!</h1>
            </div>
        </div>
        <div class="item">
            <div class="fill" style="background-image: url('../../Content/Resources/img2.jpg');"></div>
            <div class="carousel-caption">
                <h1>Poznaj naszą firmę - @Html.ActionLink("Kliknij tutaj", "About", "Home", null)</h1>
            </div>
        </div>
        <div class="item">
            <div class="fill" style="background-image: url('../../Content/Resources/img1.jpg');"></div>
            <div class="carousel-caption">
                <h1>
                    Dla nas każdy klient jest ważny
                </h1>
            </div>
        </div>
    </div>

    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="icon-prev"></span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="icon-next"></span>
    </a>
</div>

<div class="section">

    <div class="container" id="main-links">

        <div class="row">
            <div class="col-lg-4 col-md-4">
                <h3><i class="fa fa-location-arrow"></i> Śledź przesyłkę</h3>
                <p>
                    Bądź na bieżąco. Sprawdź aktualny stan swojej przesyłki.
                </p>
                @using (Html.BeginForm("Track", "Package", FormMethod.Get))
                {
                    <div class="input-group">
                        <input type="search" name="packageId" placeholder="Numer przesyłki..." class="form-control" id="track-package" />
                        <div class="input-group-btn">
                            <button class="btn btn-info">
                                <span class="glyphicon glyphicon-search"></span>
                            </button>
                        </div>
                    </div>
                }
            </div>
            <div class="col-lg-4 col-md-4">
                <h3>
                    <i class="fa fa-pencil"></i> Oblicz koszt przesyłki
                </h3>
                <p>Przejdź do formularza umożliwiającego obliczenie kosztu przesyłki</p>
                @Html.ActionLink("Oblicz koszt przesyłki", "Cost", "Package", null, new { @class = "btn btn-primary center-block" })
            </div>
            <div class="col-lg-4 col-md-4">
                <h3>
                    <i class="fa fa-folder-open"></i> Załóż konto
                </h3>
                <p>Konto klienta Instant Delivery umożliwia nadawanie paczek przez Internet.</p>
                @Html.ActionLink("Przejdź do portalu", "Index", "Portal", null, new { @class = "btn btn-primary center-block" })
            </div>
        </div>
    </div>

    <div class="section-colored">

        <div class="container">

            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <ul class="list-unstyled selling-points">
                        <li>Zapewniamy kompleksowe dostawy dla klientów indywidualnych</li>
                        <li>Jesteśmy młodą rozwijającą się firmą</li>
                        <li>Zadowolenie klienta jest naszym priorytetem</li>
                        <li>Cenimy sobie szybkość działania</li>
                        <li>Chętnie przyjmujemy uwagi od klientów na temat usług</li>
                        <li>Zapraszamy do skorzystania z naszych usług!</li>
                    </ul>
                </div>
                <div class="col-md-5">
                    <img class="img-responsive" src="../../Content/Resources/img4.jpg">
                </div>
            </div>

        </div>

    </div>
</div>

InstantDelivery.Web/Views/Home/Track.cshtml
@using InstantDelivery.Common.Extensions
@model IEnumerable<InstantDelivery.Model.Packages.PackageEventDto>

@{
    ViewBag.Title = "title";
}

<div class="container">
    <div class="section">
        <h2>Paczka numer @ViewBag.PackageId</h2>

        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Data i czas</th>
                        <th>Zdarzenie</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var dto in Model)
                    {
                        <tr>
                            <td>@dto.Date</td>
                            <td>@dto.EventType.GetDescription()</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

InstantDelivery.Web/Views/Package/Cost.cshtml
@model InstantDelivery.Web.Models.PackageCostModel
@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}
<div class="container">
    <div class="section">
        <h2>Koszt nadania paczki</h2>
        <br>
        <div class="col-lg-6 col-lg-offset-3">
            @using (Html.BeginForm("Cost", "Package", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                <div class="form-group">
                    @Html.LabelFor(m => m.Weight, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Weight, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Weight)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Length, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Length, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Length)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Width, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Width, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Width)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Height, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Height, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Height)
                    </div>
                </div>
                <input type="submit" class="btn btn-primary pull-right" value="Oblicz">
            }
        </div>
        @if (ViewBag.Cost != null)
            {
            <div class="col-lg-6 col-lg-offset-3">
                <br>
                <p class="pull-right">
                    Koszt paczki wynosi: <span class="package-cost">@ViewBag.Cost zł</span>
                </p>
            </div>
        }
    </div>
</div>

InstantDelivery.Web/Views/Package/Track.cshtml
@using InstantDelivery.Common.Extensions
@model IEnumerable<InstantDelivery.Model.Packages.PackageEventDto>

<div class="container">
    <div class="section">
        <h2>Paczka numer @ViewBag.PackageId</h2>

        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Data i czas</th>
                        <th>Zdarzenie</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var dto in Model)
                    {
                        <tr>
                            <td>@dto.Date</td>
                            <td>@dto.EventType.GetDescription()</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

InstantDelivery.Web/Views/Portal/AccountCreated.cshtml
<div class="container">
    <h3>Twoje konto zostało utworzone</h3>
    <hr>
    <p>Witamy wśród grona klientów Instant Delivery. Możesz od razu zalogować się za pomocą podanych nazwy użytkownika oraz hasła.</p>
    <br>
    <a class="btn btn-primary" href="login">Przejdź do logowania</a>
</div>

InstantDelivery.Web/Views/Portal/Index.cshtml
@{
    Layout = null;
}
<!doctype html>
<html lang="pl">
<head>
    <title>Instant Delivery</title>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta name="generator" content="Bootply" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <base href="/portal/">
    <link rel="stylesheet" href="~/Content/loading-bar.min.css" type="text/css">
    @Styles.Render("~/Content/css")
</head>
<body ng-app="app" ng-controller="MainController">
    <div id="sidebar" ng-class="{'hide-sidebar': hideSidebar || !loggedIn()}"
         class="hide-sidebar">
        <ul class="nav">
            <li><a href="packages">Moje przesyłki</a></li>
            <li><a href="sendPackage/address">Nadaj paczkę</a></li>
            <li><a href="statistics">Statystyki</a></li>
            <li><a href="profile">Mój profil</a></li>
        </ul>
    </div>
    <div id="wrapper" ng-class="{'hide-sidebar': hideSidebar || !loggedIn()}" class="hide-sidebar">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <ul class="nav navbar-nav navbar-left">
                    <li>
                        <a href="#" id="sidebar-toggle" ng-click="hideSidebar = !hideSidebar"
                           ng-show="loggedIn()">
                            <i class="fa fa-bars"></i>
                        </a>
                    </li>
                </ul>
                <a class="navbar-brand" href="/">Instant Delivery</a>
                <div class="collapse navbar-collapse navbar-ex1-collapse">
                    <ul class="nav navbar-nav navbar-right text-center">
                        <li ng-click="logOut()" ng-show="loggedIn()">
                            <a href="#">Wyloguj</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div id="main" class="container-fluid">
            <div ng-view></div>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/portal")
</body>
</html>

InstantDelivery.Web/Views/Portal/Login.cshtml
<section class="container">
    <section class="login-form">
        <form>
            <div class="outer">
                <div class="row">
                    <div class="col-xs-12">
                        <input type="text" ng-model="loginData.userName" placeholder="Nazwa użytkownika" required class="form-control" autofocus/>
                        <i class="fa fa-user"></i>
                    </div>
                    <div class="col-xs-12">
                        <input type="password" ng-model="loginData.password" placeholder="Hasło" required class="form-control"/>
                        <i class="fa fa-key"></i>
                    </div>
                </div>
                <div class="alert alert-danger" ng-show="message">{{message}}</div>
                <button type="submit" class="btn btn-block btn-info" ng-click="login()">Zaloguj</button>
            </div>
        </form>
        <section class="text-center">
            Nie posiadasz jeszcze konta? <a href="signup">Zarejestruj się</a>
        </section>
    </section>
</section>

InstantDelivery.Web/Views/Portal/MyPackages.cshtml
<h3>Moje przesyłki</h3>

<div class="datatable" id="datatable">
    <table class="table table-striped table-condensed table-hover">
        <thead>
            <tr>
                <th>Numer</th>
                <th>Status</th>
                <th>Adres</th>
                <th>Waga</th>
                <th>Wymiary</th>
            </tr>
        <tbody>
            <tr dir-paginate="package in packages | itemsPerPage: packagesPerPage" total-items="totalPackages" current-page="pagination.current">
                <td>{{package.id}}</td>
                <td>{{package.status}}</td>
                <td>
                    {{package.shippingAddress.street}} {{package.shippingAddress.number}} <br>
                    {{package.shippingAddress.postalCode}} {{package.shippingAddress.city}}, {{package.shippingAddress.country}}
                </td>
                <td>{{package.weight}} kg</td>
                <td>{{package.length}}x{{package.width}}x{{package.height}} [mm]</td>

            </tr>
        </tbody>
    </table>
    <div class="col-md-2 col-md-offset-5">
        <dir-pagination-controls on-page-change="pageChanged(newPageNumber)"></dir-pagination-controls>
    </div>
</div>

InstantDelivery.Web/Views/Portal/SendPackage.cshtml
<h2>Send package view</h2>

InstantDelivery.Web/Views/Portal/Signup.cshtml
<div class="container">
    <form class="form-horizontal" name="signupForm" novalidate>
        <h3>Dołącz do Instant Delivery</h3>
        <br>
        <div class="form-group" ng-class="{ 'has-error': signupForm.userName.$touched && signupForm.userName.$invalid }">
            <label class="col-sm-3 control-label">Nazwa użytkownika</label>
            <div class="col-sm-9">
                <input type="text" name="userName" placeholder="Nazwa użytkownika" class="form-control" autofocus
                       ng-model="signupData.userName" required>
                <div class="help-block" ng-messages="signupForm.userName.$error" ng-if="signupForm.userName.$touched && signupForm.userName.$invalid">
                    <p ng-message="required">To pole jest wymagane</p>
                </div>
            </div>
        </div>
        <div class="form-group" ng-class="{ 'has-error': signupForm.firstName.$touched && signupForm.firstName.$invalid }">
            <label class="col-sm-3 control-label">Imię</label>
            <div class="col-sm-9">
                <input type="text" name="firstName" placeholder="Imię" class="form-control" required
                       ng-model="signupData.firstName">
                <div class="help-block" ng-messages="signupForm.firstName.$error" ng-if="signupForm.firstName.$touched && signupForm.firstName.$invalid">
                    <p ng-message="required">To pole jest wymagane</p>
                </div>
            </div>
        </div>
        <div class="form-group" ng-class="{ 'has-error': signupForm.lastName.$touched && signupForm.lastName.$invalid }">
            <label class="col-sm-3 control-label">Nazwisko</label>
            <div class="col-sm-9">
                <input type="text" name="lastName" placeholder="Nazwisko" class="form-control" required
                       ng-model="signupData.lastName">
                <div class="help-block" ng-messages="signupForm.lastName.$error" ng-if="signupForm.lastName.$touched && signupForm.lastName.$invalid">
                    <p ng-message="required">To pole jest wymagane</p>
                </div>
            </div>
        </div>
        <div class="form-group" ng-class="{ 'has-error': signupForm.email.$touched && signupForm.email.$invalid }">
            <label class="col-sm-3 control-label">Email</label>
            <div class="col-sm-9">
                <input type="email" name="email" placeholder="Email" class="form-control" required
                       ng-model="signupData.email">
                <div class="help-block" ng-messages="signupForm.email.$error" ng-if="signupForm.email.$touched && signupForm.email.$invalid">
                    <p ng-message="required">To pole jest wymagane</p>
                    <p ng-message="email">Wprowadź poprawny adres email</p>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-3 control-label">Numer telefonu</label>
            <div class="col-sm-9">
                <input type="text" placeholder="Numer telefonu" class="form-control" 
                       ng-model="signupData.phoneNumber">
            </div>
        </div>
        <div class="form-group" ng-class="{ 'has-error': signupForm.password.$touched && signupForm.password.$invalid }">
            <label class="col-sm-3 control-label">Hasło</label>
            <div class="col-sm-9">
                <input type="password" name="password" placeholder="Hasło" class="form-control" required
                       ng-model="signupData.password" ng-minlength="6">
                <div class="help-block" ng-messages="signupForm.password.$error" ng-if="signupForm.password.$touched && signupForm.password.$invalid">
                    <p ng-message="required">To pole jest wymagane</p>
                    <p ng-message="minlength">Hasło musi składać się z co najmniej 6 znaków</p>
                </div>
            </div>
        </div>
        <div class="form-group" ng-class="{ 'has-error': signupForm.confirmPassword.$touched && signupForm.confirmPassword.$invalid }">
            <label class="col-sm-3 control-label">Potwierdź hasło</label>
            <div class="col-sm-9">
                <input type="password" name="confirmPassword" placeholder="Potwierdź hasło" class="form-control" required
                       ng-model="signupData.confirmPassword" input-match="signupData.password">
                <div class="help-block" ng-messages="signupForm.confirmPassword.$error" 
                     ng-if="signupForm.confirmPassword.$touched && signupForm.confirmPassword.$invalid">
                    <p ng-message="required">To pole jest wymagane</p>
                    <p ng-message="match">Hasła muszą się zgadzać</p>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="birthDate" class="col-sm-3 control-label">Data urodzenia</label>
            <div class="col-sm-3">
                <input type="date" id="birthDate" class="form-control" 
                       ng-model="signupData.dateOfBirth">
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-3">Płeć</label>
            <div class="col-sm-6">
                <div class="row">
                    <div class="col-sm-4">
                        <label class="radio-inline">
                            <input type="radio" value="male" ng-model="signupData.gender" checked>Mężczyzna
                        </label>
                    </div>
                    <div class="col-sm-4">
                        <label class="radio-inline">
                            <input type="radio" value="female" ng-model="signupData.gender">Kobieta
                        </label>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-9">
                <div class="form-group">
                    <label class="col-sm-4 control-label">Ulica</label>
                    <div class="col-sm-8">
                        <input type="text" class="form-control" ng-model="signupData.address.street">
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="form-group">
                    <label class="col-sm-6 control-label">Numer domu</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" ng-model="signupData.address.number">
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6">
                <div class="form-group">
                    <label class="col-sm-6 control-label">Kod pocztowy</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" ng-model="signupData.address.postalCode">
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <label class="col-sm-3 control-label">Miejscowość</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" ng-model="signupData.address.city">
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6">
                <div class="form-group">
                    <label class="col-sm-6 control-label">Województwo</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" ng-model="signupData.address.state">
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <label class="col-sm-3 control-label">Kraj</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" ng-model="signupData.address.country">
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-9 col-sm-offset-3">
                <div class="alert alert-danger" ng-show="message">{{message}}</div>
                <button type="submit" class="btn btn-primary btn-block" ng-click="signup(signupForm.$valid)">
                    Zarejestruj się
                </button>
            </div>
        </div>
    </form>
</div>

InstantDelivery.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>Instant Delivery</title>
    <meta name="generator" content="Bootply" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    @Styles.Render("~/Content/css")
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Instant Delivery", "Index", "Home", null, new {@class="navbar-brand"})
            </div>

            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        @Html.ActionLink("O nas", "About", "Home")
                    </li>
                    <li>
                        @Html.ActionLink("Portal", "Index", "Portal")
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    
    @RenderBody()

    <div class="container">
        <hr>
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>&copy; 2016 Marcin Chudy & Paweł Duszak</p>
                </div>
            </div>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("Scripts", required: false)
</body>
</html>